// feature name
const PROJECTS = 'PROJECTS';

export default {
  GET_LIST: `${PROJECTS}_GET_LIST`,
  SET_LIST: `${PROJECTS}_SET_LIST`,
  GET_PROJECT: `${PROJECTS}_GET_PROJECT`,
  SET_PROJECT: `${PROJECTS}_SET_PROJECT`,
  SAVE_PROJECT: `${PROJECTS}_SAVE_PROJECT`,
  DELETE_PROJECT: `${PROJECTS}_DELETE_PROJECT`,

  GET_DETAIL: `${PROJECTS}_GET_DETAIL`,
  SET_DETAIL: `${PROJECTS}_SET_DETAIL`,
  SET_GROUP: `${PROJECTS}_SET_GROUP`,
  DELETE_GROUP: `${PROJECTS}_DELETE_GROUP`,
  UPDATE_GROUP: `${PROJECTS}_UPDATE_GROUP`,
  CREATE_GROUP: `${PROJECTS}_CREATE_GROUP`,
  SORT_GROUP: `${PROJECTS}_SORT_GROUP`,
  SET_INTERFACE: `${PROJECTS}_SET_INTERFACE`,
  DELETE_INTERFACE: `${PROJECTS}_DELETE_INTERFACE`,
  CREATE_INTERFACE: `${PROJECTS}_CREATE_INTERFACE`,
  UPDATE_INTERFACE: `${PROJECTS}_UPDATE_INTERFACE`,
  SORT_INTERFACE: `${PROJECTS}_SORT_INTERFACE`,
}
